### ISSUE TITLE
FreeBSD compile errors

### ISSUE THREAD

**Issue by artorlov** [kaltura/nginx-vod-module#662]
/root/nginx-vod-module/ngx_buffer_cache.h:62:40: error: no newline at end of file
*** [objs/addon/nginx-vod-module/ngx_buffer_cache.o] Error code 1

/root/nginx-vod-module/vod/subtitle/dfxp_format.c:952:7: error: no newline at end of file
*** [objs/addon/subtitle/dfxp_format.o] Error code 1

simple fix - add new line at the end of files

**Comment by erankor** [comment]
Thanks for reporting - https://github.com/kaltura/nginx-vod-module/pull/663
Will merge after Travis completes

**Comment by erankor** [comment]
Merged, please let me know if there are additional errors

**Comment by jessp01** [comment]
I was able to compile using FreeBSD clang version 4.0.0 on FreeBSD 11.1-BETA3. I believe this can be closed.

**Comment by erankor** [comment]
Thanks @jessp01, closing
