### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ebumalik** [kaltura/nginx-vod-module#490]
Hi,

I am trying to build the vod module with nginx 1.2.4 using gcc 4.8.4 (Ubuntu 14.04.2) but unfortunately I am getting this error. 

`make -f objs/Makefile
make[1]: Entering directory `/home/ubuntu/nginx-1.2.4'
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I/home/ubuntu/nginx-rtmp-module  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
		-o objs/addon/nginx-vod-module/ngx_child_http_request.o \
		/home/ubuntu/nginx-vod-module/ngx_child_http_request.c
In file included from /usr/include/x86_64-linux-gnu/sys/sysctl.h:23:0,
                 from src/os/unix/ngx_linux_config.h:54,
                 from src/core/ngx_config.h:26,
                 from /home/ubuntu/nginx-vod-module/ngx_child_http_request.c:1:
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:76:28: error: ‘ngx_http_headers_in_t’ has no member named ‘if_match’
  { ngx_string("If-Match"), offsetof(ngx_http_headers_in_t, if_match) },
                            ^
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:76:2: error: missing initializer for field ‘offset’ of ‘ngx_child_request_hide_header_t’ [-Werror=missing-field-initializers]
  { ngx_string("If-Match"), offsetof(ngx_http_headers_in_t, if_match) },
  ^
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:41:8: note: ‘offset’ declared here
  off_t offset;
        ^
In file included from /usr/include/x86_64-linux-gnu/sys/sysctl.h:23:0,
                 from src/os/unix/ngx_linux_config.h:54,
                 from src/core/ngx_config.h:26,
                 from /home/ubuntu/nginx-vod-module/ngx_child_http_request.c:1:
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:78:33: error: ‘ngx_http_headers_in_t’ has no member named ‘if_none_match’
  { ngx_string("If-None-Match"), offsetof(ngx_http_headers_in_t, if_none_match) },
                                 ^
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:78:2: error: missing initializer for field ‘name’ of ‘ngx_child_request_hide_header_t’ [-Werror=missing-field-initializers]
  { ngx_string("If-None-Match"), offsetof(ngx_http_headers_in_t, if_none_match) },
  ^
/home/ubuntu/nginx-vod-module/ngx_child_http_request.c:40:12: note: ‘name’ declared here
  ngx_str_t name;
            ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/nginx-vod-module/ngx_child_http_request.o] Error 1
make[1]: Leaving directory `/home/ubuntu/nginx-1.2.4'
make: *** [build] Error 2
`
Thanks.

**Comment by erankor** [comment]
This is a very old version of nginx, you can work around this error by commenting this line (ngx_child_http_request.c:78)

**Comment by erankor** [comment]
@ebumalik, did it work for you? can we close this issue?

**Comment by ebumalik** [comment]
yes it worked with 1.10.2 stable version of nginx. thank you.
