### ISSUE TITLE
avcodec_decode_video2 is deprecated in ffmpeg 3.1

### ISSUE THREAD

**Issue by dennissch** [kaltura/nginx-vod-module#370]
Hi, 
we can't compile because "avcodec_decode_video2" is deprecated in newer ffmpeg versions (https://xpra.org/trac/ticket/1242). 

Make throws this error:

`../nginx-vod-module/vod/thumb/thumb_grabber.c: In function 'thumb_grabber_decode_frame':
../nginx-vod-module/vod/thumb/thumb_grabber.c:453:2: error: 'avcodec_decode_video2' is deprecated (declared at /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:4763) [-Werror=deprecated-declarations]
  avrc = avcodec_decode_video2(state->decoder, state->decoded_frame, &state->has_frame, &input_packet);
  ^
../nginx-vod-module/vod/thumb/thumb_grabber.c: In function 'thumb_grabber_write_frame':
../nginx-vod-module/vod/thumb/thumb_grabber.c:494:2: error: 'avcodec_encode_video2' is deprecated (declared at /usr/include/x86_64-linux-gnu/libavcodec/avcodec.h:5271) [-Werror=deprecated-declarations]
  avrc = avcodec_encode_video2(state->encoder, &state->output_packet, state->decoded_frame, &got_packet);
  ^
cc1: all warnings being treated as errors
objs/Makefile:2319: recipe for target 'objs/addon/thumb/thumb_grabber.o' failed
make[1]: *** [objs/addon/thumb/thumb_grabber.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.11.2'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2`

Is it possible to compile with ffmpeg 3.1? Thanks for your help!

**Comment by erankor** [comment]
Hi,

I do not currently plan to upgrade, it seems ffmpeg change their API quite frequently...
Easiest workaround I can suggest is to remove nginx's default 'treat warnings as errors' so that it will compile, this is explained in this comment - https://github.com/kaltura/nginx-vod-module/issues/81#issuecomment-94190152

**Comment by dennissch** [comment]
Thanks, it works :)
